### ISSUE TITLE
Student Semester Registration Issue

### ISSUE THREAD

**Issue by iamwebsurgeon** [hrshadhin/osums#16]
Student semester registration is not populating any data of admitted students. Can you give me a solution? I am trying to find it but couldn't get it where is the problem.

OS: Windows 10 64bit
Server: Apache - Wamp
PHP Version: 7.3.1
MySQL Version: 5.7.26

**Comment by hrshadhin** [comment]
Can you tell me details about it. What you did after installation? And also which menu are referring to?
And please debug this method. I seeing everything fine here.
https://github.com/hrshadhin/osums/blob/master/app/Http/Controllers/studentController.php#L115
