### ISSUE TITLE
How it works your licence  AGPL-3.0 license?

### ISSUE THREAD

**Issue by theteacherx** [hrshadhin/osums#18]
- Can I fork your code and make my own changes to make sense with my country traditions?
- Can I install my fork on a server and offer to schools or universities for free?
- Can I install my fork on a server and offer to schools or universities charging something
?
- Maybe another license could be more close to your goal: https://choosealicense.com/ 
- If you think it's convenient, check this post about your license:
 https://www.techrepublic.com/blog/10-things/dont-believe-the-hype-agpl-open-source-licensing-is-toxic-and-unpopular/

I appreciate your work. Its very interesting and useful!

Thanks!

**Comment by hrshadhin** [comment]
Thanks for raising a issue about it. I choose that license because that is perfect for my application. i don't follow those bullshits blogger, i read every license first before i choose it. Read license first! you
will got your answers, that you asked here.
