### ISSUE TITLE
Submit new attendance is disabled

### ISSUE THREAD

**Issue by jrichardsz** [hrshadhin/osums#7]
## Expected Behavior
When I want to register or add new attendance, submit button is disabled.

## Current Behavior
When I want to register or add new attendance, submit button must be enabled.

## Steps to Reproduce

1. Login as admin
2. Go to attendance option and click in **new** option
3. At this moment is possible to view the submit button but, a few milli-seconds after, button dissapear.
3. Fill the required inputs 
4. There is not a submit button to complete the operation.

**Comment by hrshadhin** [comment]
Did you have any student? After fill up the form student list should be shown. if have student then submit button will be show up.

**Comment by jrichardsz** [comment]
I am review this demo : http://osums.hrshadhin.me

I have been created : department, subject and student :

![screenshot from 2018-12-08 18 36 16 - student list](https://user-images.githubusercontent.com/3322836/49691805-7c6b6500-fb18-11e8-9fb4-f0852f0bff09.png)

 But in attendance page, submit button suddenly disappear:

![screenshot from 2018-12-08 18 36 53 - attendance](https://user-images.githubusercontent.com/3322836/49691811-8db47180-fb18-11e8-8864-4bb0f8dc80fc.png)

Need I configure another pages?

Thanks in advance.

**Comment by hrshadhin** [comment]
You have to registered the student in semester. You just admit the student only.
http://osums.hrshadhin.me/student-registration

**Comment by jrichardsz** [comment]
I will try again asap and share my result!!
Thanks

**Comment by jrichardsz** [comment]
It works.
Thanks
