### ISSUE TITLE
Student wise error

### ISSUE THREAD

**Issue by jrichardsz** [hrshadhin/osums#8]
I fill all the required information and when I press "get transcript" I get this error:

![student_wise_error](https://user-images.githubusercontent.com/3322836/51294757-69369980-19e2-11e9-9dfd-9d714f66d5f0.png)

**Comment by hrshadhin** [comment]
Did you entry the marks and publish the result?

**Comment by jrichardsz** [comment]
What is mark and how can I publish the result?

I reviewed and does not exist in the main page : 

![main](https://raw.githubusercontent.com/hrshadhin/osums/master/screenshots/1.png)

Thanks.

**Comment by hrshadhin** [comment]
Here the error message is self explanatory. 
Before create any useless issue, do those things first. 
1. setup institution information 
2. Add department
3. Create subject for the department
4. admit student and register those student in semester
5. Add exam marks for them
5. View the result.
