### ISSUE TITLE
Subject wise error

### ISSUE THREAD

**Issue by jrichardsz** [hrshadhin/osums#9]
I fill all the required information and when I press "get result sheet" I get this error:
![subject_wise_error](https://user-images.githubusercontent.com/3322836/51294799-997e3800-19e2-11e9-94d1-7a5d832f27d2.png)

**Comment by hrshadhin** [comment]
Here the error message is self explanatory. 
Before create any useless issue, do those things first. 
1. setup institution information 
2. Add department
3. Create subject for the department
4. admit student and register those student in semester
5. Add exam marks for them
5. View the result.
